name: documentation-generation
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gen-docs:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper


    - name: Git pull
      working-directory: main
      run: git pull

    - name: Generate documentation
      working-directory: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify docs --jobs $(nproc)